
version: '3'
services:

  django_app:
    build: .
    container_name: pizza_order_service
    ports:
      - '8000:8000'

  postgres:
    image: postgres:10.3
    container_name: postgres
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: