
version: '3'
services:

  django_app:
    build: .
    container_name: pizza_order_service
    ports:
      - '8000:8000'
    networks:
        - one_network
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:10.3
    container_name: postgres_db
    ports:
      - '6500:5432'
    restart: always
    networks:
        - one_network
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:

networks:
  one_network: